import SwiftUI

extension SceneTheme {
    static func theme(for id: SceneThemeID) -> SceneTheme {
        switch id {
        case .cleanCanvas:
            return SceneTheme(
                id: .cleanCanvas,
                displayName: "Clean Canvas",
                isDark: false,
                backgroundType: .none,
                appBackground: Color(hex: 0xF7F6F2),
                sidebarBackground: Color(hex: 0xF1F0EC),
                readerBackground: Color(hex: 0xFCFBF8),
                secondarySurface: Color(hex: 0xF3F1EC),
                primaryText: Color(hex: 0x292824),
                secondaryText: Color(hex: 0x706E68),
                tertiaryText: Color(hex: 0x96938B),
                border: Color(hex: 0xE4E1DA),
                divider: Color(hex: 0xE8E5DE),
                hoverBackground: Color(hex: 0xECEAE4),
                selectedBackground: Color(hex: 0xE6EAF5),
                accent: Color(hex: 0x5B6FA8),
                accentSoft: Color(hex: 0xE6EAF5),
                codeBackground: Color(hex: 0xF3F1EC),
                inlineCodeBackground: Color(hex: 0xF0EDE6),
                tableHeaderBackground: Color(hex: 0xF1EFEA),
                blockquoteBackground: Color(hex: 0xF5F3EE),
                cssAppBg: "#F7F6F2", cssReaderBg: "#FCFBF8",
                cssPrimaryText: "#292824", cssSecondaryText: "#706E68",
                cssBorder: "#E4E1DA", cssDivider: "#E8E5DE", cssSecondarySurface: "#F3F1EC",
                cssAccent: "#5B6FA8", cssAccentSoft: "#E6EAF5",
                cssCodeBg: "#F3F1EC", cssTableHeaderBg: "#F1EFEA", cssBlockquoteBg: "#F5F3EE",
                cssHighlightBg: "rgba(91, 111, 168, 0.18)"
            )
        case .warmLibrary:
            return SceneTheme(
                id: .warmLibrary,
                displayName: "Warm Library",
                isDark: false,
                backgroundType: .warmNoise,
                appBackground: Color(hex: 0xF0E8D8),
                sidebarBackground: Color(hex: 0xEBE3D2),
                readerBackground: Color(hex: 0xF5EFE2),
                secondarySurface: Color(hex: 0xEAE2D0),
                primaryText: Color(hex: 0x3B2E1E),
                secondaryText: Color(hex: 0x7A6F5E),
                tertiaryText: Color(hex: 0x9E937F),
                border: Color(hex: 0xD8CDB8),
                divider: Color(hex: 0xDDD2BD),
                hoverBackground: Color(hex: 0xE5DCCA),
                selectedBackground: Color(hex: 0xF5EDE1),
                accent: Color(hex: 0xC47D2E),
                accentSoft: Color(hex: 0xF5EDE1),
                codeBackground: Color(hex: 0xEAE2D0),
                inlineCodeBackground: Color(hex: 0xE6DDC9),
                tableHeaderBackground: Color(hex: 0xE8E0CE),
                blockquoteBackground: Color(hex: 0xEDE5D5),
                cssAppBg: "#F0E8D8", cssReaderBg: "#F5EFE2",
                cssPrimaryText: "#3B2E1E", cssSecondaryText: "#7A6F5E",
                cssBorder: "#D8CDB8", cssDivider: "#DDD2BD", cssSecondarySurface: "#EAE2D0",
                cssAccent: "#C47D2E", cssAccentSoft: "#F5EDE1",
                cssCodeBg: "#EAE2D0", cssTableHeaderBg: "#E8E0CE", cssBlockquoteBg: "#EDE5D5",
                cssHighlightBg: "rgba(196, 125, 46, 0.18)"
            )
        case .aurora:
            return SceneTheme(
                id: .aurora,
                displayName: "Aurora",
                isDark: true,
                backgroundType: .aurora,
                appBackground: Color(hex: 0x1A1C29),
                sidebarBackground: Color(hex: 0x1E2032).opacity(0.6),
                readerBackground: Color(hex: 0x141620),
                secondarySurface: Color(hex: 0x272A3C),
                primaryText: Color(hex: 0xEAE8FA),
                secondaryText: Color(hex: 0xA3A0D1),
                tertiaryText: Color(hex: 0x7875A8),
                border: Color(hex: 0x363854),
                divider: Color(hex: 0x2C2E4A),
                hoverBackground: Color(hex: 0x2A2C46),
                selectedBackground: Color(hex: 0x383060),
                accent: Color(hex: 0x8C78ED),
                accentSoft: Color(hex: 0x383060),
                codeBackground: Color(hex: 0x1B1D2C),
                inlineCodeBackground: Color(hex: 0x1F2134),
                tableHeaderBackground: Color(hex: 0x1D1F2E),
                blockquoteBackground: Color(hex: 0x181A25),
                cssAppBg: "#1A1C29", cssReaderBg: "rgba(20, 22, 32, 0.85)",
                cssPrimaryText: "#EAE8FA", cssSecondaryText: "#A3A0D1",
                cssBorder: "#363854", cssDivider: "#2C2E4A", cssSecondarySurface: "#272A3C",
                cssAccent: "#8C78ED", cssAccentSoft: "#383060",
                cssCodeBg: "#1B1D2C", cssTableHeaderBg: "#1D1F2E", cssBlockquoteBg: "#181A25",
                cssHighlightBg: "rgba(140, 120, 237, 0.25)"
            )
        case .midnightNebula:
            return SceneTheme(
                id: .midnightNebula,
                displayName: "Midnight Nebula",
                isDark: true,
                backgroundType: .stars,
                appBackground: Color(hex: 0x0C0D14),
                sidebarBackground: Color(hex: 0x10111A).opacity(0.7),
                readerBackground: Color(hex: 0x0A0B10),
                secondarySurface: Color(hex: 0x1C1D2A),
                primaryText: Color(hex: 0xE7E5DF),
                secondaryText: Color(hex: 0x8A889A),
                tertiaryText: Color(hex: 0x5C5A6A),
                border: Color(hex: 0x282A36),
                divider: Color(hex: 0x242630),
                hoverBackground: Color(hex: 0x20222C),
                selectedBackground: Color(hex: 0x2E3548),
                accent: Color(hex: 0x7B93D4),
                accentSoft: Color(hex: 0x2E3548),
                codeBackground: Color(hex: 0x141620),
                inlineCodeBackground: Color(hex: 0x181A26),
                tableHeaderBackground: Color(hex: 0x161822),
                blockquoteBackground: Color(hex: 0x10121A),
                cssAppBg: "#0C0D14", cssReaderBg: "rgba(10, 11, 16, 0.85)",
                cssPrimaryText: "#E7E5DF", cssSecondaryText: "#8A889A",
                cssBorder: "#282A36", cssDivider: "#242630", cssSecondarySurface: "#1C1D2A",
                cssAccent: "#7B93D4", cssAccentSoft: "#2E3548",
                cssCodeBg: "#141620", cssTableHeaderBg: "#161822", cssBlockquoteBg: "#10121A",
                cssHighlightBg: "rgba(123, 147, 212, 0.25)"
            )
        case .blueprint:
            return SceneTheme(
                id: .blueprint,
                displayName: "Blueprint",
                isDark: true,
                backgroundType: .blueprint,
                appBackground: Color(hex: 0x0B1D3A),
                sidebarBackground: Color(hex: 0x10254A).opacity(0.8),
                readerBackground: Color(hex: 0x0A1830),
                secondarySurface: Color(hex: 0x1C355F),
                primaryText: Color(hex: 0xE0EAF5),
                secondaryText: Color(hex: 0x8CA8C4),
                tertiaryText: Color(hex: 0x5D7A9E),
                border: Color(hex: 0x2C4A7A),
                divider: Color(hex: 0x243E6B),
                hoverBackground: Color(hex: 0x18305A),
                selectedBackground: Color(hex: 0x25467A),
                accent: Color(hex: 0x5AC8FA),
                accentSoft: Color(hex: 0x25467A),
                codeBackground: Color(hex: 0x122545),
                inlineCodeBackground: Color(hex: 0x162A4F),
                tableHeaderBackground: Color(hex: 0x14284A),
                blockquoteBackground: Color(hex: 0x0C1C38),
                cssAppBg: "#0B1D3A", cssReaderBg: "rgba(10, 24, 48, 0.85)",
                cssPrimaryText: "#E0EAF5", cssSecondaryText: "#8CA8C4",
                cssBorder: "#2C4A7A", cssDivider: "#243E6B", cssSecondarySurface: "#1C355F",
                cssAccent: "#5AC8FA", cssAccentSoft: "#25467A",
                cssCodeBg: "#122545", cssTableHeaderBg: "#14284A", cssBlockquoteBg: "#0C1C38",
                cssHighlightBg: "rgba(90, 200, 250, 0.20)"
            )
        case .forestTerminal:
            return SceneTheme(
                id: .forestTerminal,
                displayName: "Forest Terminal",
                isDark: true,
                backgroundType: .forest,
                appBackground: Color(hex: 0x161C16),
                sidebarBackground: Color(hex: 0x1B231B).opacity(0.8),
                readerBackground: Color(hex: 0x121612),
                secondarySurface: Color(hex: 0x242E24),
                primaryText: Color(hex: 0xC3D6C3),
                secondaryText: Color(hex: 0x859E85),
                tertiaryText: Color(hex: 0x5A705A),
                border: Color(hex: 0x354535),
                divider: Color(hex: 0x2A382A),
                hoverBackground: Color(hex: 0x202B20),
                selectedBackground: Color(hex: 0x2A3D2A),
                accent: Color(hex: 0x7CC27C),
                accentSoft: Color(hex: 0x2A3D2A),
                codeBackground: Color(hex: 0x182018),
                inlineCodeBackground: Color(hex: 0x1C251C),
                tableHeaderBackground: Color(hex: 0x1A221A),
                blockquoteBackground: Color(hex: 0x141A14),
                cssAppBg: "#161C16", cssReaderBg: "rgba(18, 22, 18, 0.85)",
                cssPrimaryText: "#C3D6C3", cssSecondaryText: "#859E85",
                cssBorder: "#354535", cssDivider: "#2A382A", cssSecondarySurface: "#242E24",
                cssAccent: "#7CC27C", cssAccentSoft: "#2A3D2A",
                cssCodeBg: "#182018", cssTableHeaderBg: "#1A221A", cssBlockquoteBg: "#141A14",
                cssHighlightBg: "rgba(124, 194, 124, 0.22)"
            )
        case .sepia:
            return SceneTheme(
                id: .sepia, displayName: "Sepia", isDark: false, backgroundType: .warmNoise,
                appBackground: Color(hex: 0xF4ECD8), sidebarBackground: Color(hex: 0xEDE3CC),
                readerBackground: Color(hex: 0xFAF3E3), secondarySurface: Color(hex: 0xE8DCC8),
                primaryText: Color(hex: 0x3D2B1F), secondaryText: Color(hex: 0x7B6051),
                tertiaryText: Color(hex: 0xA08070), border: Color(hex: 0xD4C4A8),
                divider: Color(hex: 0xD9CDB0), hoverBackground: Color(hex: 0xE8DCC0),
                selectedBackground: Color(hex: 0xEBDFC8), accent: Color(hex: 0x8B5E3C),
                accentSoft: Color(hex: 0xF0E4D4), codeBackground: Color(hex: 0xEDE3CC),
                inlineCodeBackground: Color(hex: 0xE8DCCA), tableHeaderBackground: Color(hex: 0xEAE0CB),
                blockquoteBackground: Color(hex: 0xEDE5D4),
                cssAppBg: "#F4ECD8", cssReaderBg: "#FAF3E3",
                cssPrimaryText: "#3D2B1F", cssSecondaryText: "#7B6051",
                cssBorder: "#D4C4A8", cssDivider: "#D9CDB0", cssSecondarySurface: "#E8DCC8",
                cssAccent: "#8B5E3C", cssAccentSoft: "#F0E4D4",
                cssCodeBg: "#EDE3CC", cssTableHeaderBg: "#EAE0CB", cssBlockquoteBg: "#EDE5D4",
                cssHighlightBg: "rgba(139, 94, 60, 0.18)"
            )
        case .nord:
            return SceneTheme(
                id: .nord, displayName: "Nord", isDark: true, backgroundType: .none,
                appBackground: Color(hex: 0x2E3440), sidebarBackground: Color(hex: 0x272C38),
                readerBackground: Color(hex: 0x3B4252), secondarySurface: Color(hex: 0x434C5E),
                primaryText: Color(hex: 0xECEFF4), secondaryText: Color(hex: 0xD8DEE9),
                tertiaryText: Color(hex: 0xB0BAC8), border: Color(hex: 0x434C5E),
                divider: Color(hex: 0x3D4557), hoverBackground: Color(hex: 0x3D4559),
                selectedBackground: Color(hex: 0x4C566A), accent: Color(hex: 0x88C0D0),
                accentSoft: Color(hex: 0x3D4B56), codeBackground: Color(hex: 0x2E3440),
                inlineCodeBackground: Color(hex: 0x2A3040), tableHeaderBackground: Color(hex: 0x323A4A),
                blockquoteBackground: Color(hex: 0x2C3346),
                cssAppBg: "#2E3440", cssReaderBg: "#3B4252",
                cssPrimaryText: "#ECEFF4", cssSecondaryText: "#D8DEE9",
                cssBorder: "#434C5E", cssDivider: "#3D4557", cssSecondarySurface: "#434C5E",
                cssAccent: "#88C0D0", cssAccentSoft: "#3D4B56",
                cssCodeBg: "#2E3440", cssTableHeaderBg: "#323A4A", cssBlockquoteBg: "#2C3346",
                cssHighlightBg: "rgba(136, 192, 208, 0.22)"
            )
        case .solarizedLight:
            return SceneTheme(
                id: .solarizedLight, displayName: "Solarized Light", isDark: false, backgroundType: .none,
                appBackground: Color(hex: 0xEEE8D5), sidebarBackground: Color(hex: 0xE8E2CF),
                readerBackground: Color(hex: 0xFDF6E3), secondarySurface: Color(hex: 0xE5DFC8),
                primaryText: Color(hex: 0x586E75), secondaryText: Color(hex: 0x657B83),
                tertiaryText: Color(hex: 0x839496), border: Color(hex: 0xD2C9A5),
                divider: Color(hex: 0xDAD1AD), hoverBackground: Color(hex: 0xE5DFC8),
                selectedBackground: Color(hex: 0xE8E1CE), accent: Color(hex: 0x268BD2),
                accentSoft: Color(hex: 0xE0EEF8), codeBackground: Color(hex: 0xEEE8D5),
                inlineCodeBackground: Color(hex: 0xE8E2D0), tableHeaderBackground: Color(hex: 0xE6DFC9),
                blockquoteBackground: Color(hex: 0xEDE7D3),
                cssAppBg: "#EEE8D5", cssReaderBg: "#FDF6E3",
                cssPrimaryText: "#586E75", cssSecondaryText: "#657B83",
                cssBorder: "#D2C9A5", cssDivider: "#DAD1AD", cssSecondarySurface: "#E5DFC8",
                cssAccent: "#268BD2", cssAccentSoft: "#E0EEF8",
                cssCodeBg: "#EEE8D5", cssTableHeaderBg: "#E6DFC9", cssBlockquoteBg: "#EDE7D3",
                cssHighlightBg: "rgba(38, 139, 210, 0.15)"
            )
        case .solarizedDark:
            return SceneTheme(
                id: .solarizedDark, displayName: "Solarized Dark", isDark: true, backgroundType: .none,
                appBackground: Color(hex: 0x002B36), sidebarBackground: Color(hex: 0x00232C),
                readerBackground: Color(hex: 0x073642), secondarySurface: Color(hex: 0x0D4A5C),
                primaryText: Color(hex: 0x839496), secondaryText: Color(hex: 0x657B83),
                tertiaryText: Color(hex: 0x4F6A72), border: Color(hex: 0x0D4A5C),
                divider: Color(hex: 0x084A5B), hoverBackground: Color(hex: 0x0A3A48),
                selectedBackground: Color(hex: 0x0F4555), accent: Color(hex: 0x268BD2),
                accentSoft: Color(hex: 0x0A3050), codeBackground: Color(hex: 0x002B36),
                inlineCodeBackground: Color(hex: 0x002330), tableHeaderBackground: Color(hex: 0x023040),
                blockquoteBackground: Color(hex: 0x00262F),
                cssAppBg: "#002B36", cssReaderBg: "#073642",
                cssPrimaryText: "#839496", cssSecondaryText: "#657B83",
                cssBorder: "#0D4A5C", cssDivider: "#084A5B", cssSecondarySurface: "#0D4A5C",
                cssAccent: "#268BD2", cssAccentSoft: "#0A3050",
                cssCodeBg: "#002B36", cssTableHeaderBg: "#023040", cssBlockquoteBg: "#00262F",
                cssHighlightBg: "rgba(38, 139, 210, 0.22)"
            )
        case .gruvboxLight:
            return SceneTheme(
                id: .gruvboxLight, displayName: "Gruvbox Light", isDark: false, backgroundType: .warmNoise,
                appBackground: Color(hex: 0xF2E5BC), sidebarBackground: Color(hex: 0xEBDBB2),
                readerBackground: Color(hex: 0xFBF1C7), secondarySurface: Color(hex: 0xE5D4A8),
                primaryText: Color(hex: 0x3C3836), secondaryText: Color(hex: 0x504945),
                tertiaryText: Color(hex: 0x7C6F64), border: Color(hex: 0xD5C4A1),
                divider: Color(hex: 0xDACCAA), hoverBackground: Color(hex: 0xE5D5A8),
                selectedBackground: Color(hex: 0xEAD9A8), accent: Color(hex: 0xD79921),
                accentSoft: Color(hex: 0xF8EEC0), codeBackground: Color(hex: 0xEBDBB2),
                inlineCodeBackground: Color(hex: 0xE5D4AA), tableHeaderBackground: Color(hex: 0xE8D8A8),
                blockquoteBackground: Color(hex: 0xEEDDB8),
                cssAppBg: "#F2E5BC", cssReaderBg: "#FBF1C7",
                cssPrimaryText: "#3C3836", cssSecondaryText: "#504945",
                cssBorder: "#D5C4A1", cssDivider: "#DACCAA", cssSecondarySurface: "#E5D4A8",
                cssAccent: "#D79921", cssAccentSoft: "#F8EEC0",
                cssCodeBg: "#EBDBB2", cssTableHeaderBg: "#E8D8A8", cssBlockquoteBg: "#EEDDB8",
                cssHighlightBg: "rgba(215, 153, 33, 0.20)"
            )
        case .dracula:
            return SceneTheme(
                id: .dracula, displayName: "Dracula", isDark: true, backgroundType: .none,
                appBackground: Color(hex: 0x282A36), sidebarBackground: Color(hex: 0x21222C),
                readerBackground: Color(hex: 0x1E1F29), secondarySurface: Color(hex: 0x44475A),
                primaryText: Color(hex: 0xF8F8F2), secondaryText: Color(hex: 0xBBBBBB),
                tertiaryText: Color(hex: 0x908080), border: Color(hex: 0x44475A),
                divider: Color(hex: 0x363849), hoverBackground: Color(hex: 0x323547),
                selectedBackground: Color(hex: 0x3E4159), accent: Color(hex: 0xBD93F9),
                accentSoft: Color(hex: 0x3D3560), codeBackground: Color(hex: 0x21222C),
                inlineCodeBackground: Color(hex: 0x1E1F2A), tableHeaderBackground: Color(hex: 0x262832),
                blockquoteBackground: Color(hex: 0x242532),
                cssAppBg: "#282A36", cssReaderBg: "#1E1F29",
                cssPrimaryText: "#F8F8F2", cssSecondaryText: "#BBBBBB",
                cssBorder: "#44475A", cssDivider: "#363849", cssSecondarySurface: "#44475A",
                cssAccent: "#BD93F9", cssAccentSoft: "#3D3560",
                cssCodeBg: "#21222C", cssTableHeaderBg: "#262832", cssBlockquoteBg: "#242532",
                cssHighlightBg: "rgba(189, 147, 249, 0.22)"
            )
        case .catppuccinLatte:
            return SceneTheme(
                id: .catppuccinLatte, displayName: "Catppuccin Latte", isDark: false, backgroundType: .none,
                appBackground: Color(hex: 0xDCE0E8), sidebarBackground: Color(hex: 0xD5D9E3),
                readerBackground: Color(hex: 0xEFF1F5), secondarySurface: Color(hex: 0xD8DCE6),
                primaryText: Color(hex: 0x4C4F69), secondaryText: Color(hex: 0x6C6F85),
                tertiaryText: Color(hex: 0x8C8FA1), border: Color(hex: 0xBCC0CC),
                divider: Color(hex: 0xC5C8D5), hoverBackground: Color(hex: 0xE0E3EA),
                selectedBackground: Color(hex: 0xE5E8EE), accent: Color(hex: 0x8839EF),
                accentSoft: Color(hex: 0xEDE3FC), codeBackground: Color(hex: 0xD5D9E3),
                inlineCodeBackground: Color(hex: 0xD0D4DE), tableHeaderBackground: Color(hex: 0xD8DCE4),
                blockquoteBackground: Color(hex: 0xDDDFE7),
                cssAppBg: "#DCE0E8", cssReaderBg: "#EFF1F5",
                cssPrimaryText: "#4C4F69", cssSecondaryText: "#6C6F85",
                cssBorder: "#BCC0CC", cssDivider: "#C5C8D5", cssSecondarySurface: "#D8DCE6",
                cssAccent: "#8839EF", cssAccentSoft: "#EDE3FC",
                cssCodeBg: "#D5D9E3", cssTableHeaderBg: "#D8DCE4", cssBlockquoteBg: "#DDDFE7",
                cssHighlightBg: "rgba(136, 57, 239, 0.15)"
            )
        case .catppuccinMocha:
            return SceneTheme(
                id: .catppuccinMocha, displayName: "Catppuccin Mocha", isDark: true, backgroundType: .none,
                appBackground: Color(hex: 0x181825), sidebarBackground: Color(hex: 0x11111B),
                readerBackground: Color(hex: 0x1E1E2E), secondarySurface: Color(hex: 0x313244),
                primaryText: Color(hex: 0xCDD6F4), secondaryText: Color(hex: 0xBAC2DE),
                tertiaryText: Color(hex: 0xA6ADC8), border: Color(hex: 0x313244),
                divider: Color(hex: 0x2A2B3C), hoverBackground: Color(hex: 0x252535),
                selectedBackground: Color(hex: 0x302D55), accent: Color(hex: 0xCBA6F7),
                accentSoft: Color(hex: 0x302845), codeBackground: Color(hex: 0x181825),
                inlineCodeBackground: Color(hex: 0x151520), tableHeaderBackground: Color(hex: 0x1C1C2E),
                blockquoteBackground: Color(hex: 0x16162A),
                cssAppBg: "#181825", cssReaderBg: "#1E1E2E",
                cssPrimaryText: "#CDD6F4", cssSecondaryText: "#BAC2DE",
                cssBorder: "#313244", cssDivider: "#2A2B3C", cssSecondarySurface: "#313244",
                cssAccent: "#CBA6F7", cssAccentSoft: "#302845",
                cssCodeBg: "#181825", cssTableHeaderBg: "#1C1C2E", cssBlockquoteBg: "#16162A",
                cssHighlightBg: "rgba(203, 166, 247, 0.22)"
            )
        }
    }
}
